---
# Installation from openjdk17 docs:
# sudo apt update
# sudo apt install fontconfig openjdk-17-jre
# java -version
# openjdk version "17.0.13" 2024-10-15
# OpenJDK Runtime Environment (build 17.0.13+11-Debian-2)
# OpenJDK 64-Bit Server VM (build 17.0.13+11-Debian-2, mixed mode, sharing)

- name: Install OpenJDK 17 on a Ubuntu machine
  hosts: jenkins-vm
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install OpenJDK 17
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - fontconfig
        - openjdk-17-jre

    - name: Check Java version
      ansible.builtin.command:
        cmd: java -version
      register: java_version
      changed_when: false
      failed_when: java_version.rc != 0

    - name: Print Java version
      ansible.builtin.debug:
        msg: "{{ java_version.stderr }}"
