---
- name: Install Docker engine on a Ubuntu machine
  hosts: jenkins-vm
  become: true
  tasks:
    - name: Add Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker.asc
        mode: '644'

    - name: Get dpkg print architecture
      ansible.builtin.command: dpkg --print-architecture
      register: dpkg_print_architecture
      changed_when: false

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/docker.asc arch={{ dpkg_print_architecture.stdout }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - ca-certificates
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Start Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
